version: '3.8'

services:

    backend:
        image: backend_example:latest
        build: ~/devops_docker_temp/part_1/material-applications/example-backend
        ports:
            - 8081:8081
        container_name: compose_backend
    frontend:
        image: frontend_example:latest
        build: ~/devops_docker_temp/part_1/material-applications/example-frontend
        ports:
            - 80:8080
        container_name: compose_frontend

