version: '3.8'

services:

    backend:
        image: backend_example:latest
        build: ~/devops_docker_temp/part_1/material-applications/example-backend
        ports:
            - 8081:8081
        container_name: compose_backend

    frontend:
        image: frontend_example:latest
        build: ~/devops_docker_temp/part_1/material-applications/example-frontend
        ports:
            - 80:8080
        container_name: compose_frontend

    redis_base:
        image: redis:latest
        command: ["redis-server"]
        container_name: redis_base

    postgres_db:
        image: postgres:13.2-alpine
        restart: unless-stopped
        container_name: postgres_db
        environment:
            POSTGRES_HOST: postgres_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
        volumes:
          - database:/var/lib/postgresql/data

volumes:
  database:
